name: Sync Fork

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "false" # 不拉取 submodules

      - name: Set Git environment variables
        run: |
          echo "GIT_TERMINAL_PROMPT=0" >> $GITHUB_ENV

      - name: Set up Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Sync with upstream (只更新 docs 資料夾)
        run: |
          # 添加上游遠端儲存庫
          git remote add upstream https://github.com/n8n-io/n8n-docs.git
          git fetch upstream

          # 切換到主分支
          git checkout main

          # 僅更新 docs 資料夾，忽略 submodules 和其他文件
          git checkout upstream/main -- docs

          # 提交變更
          git add docs
          git commit -m "Sync docs folder from upstream" || echo "沒有變更需要提交"

      - name: Push to origin
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
