name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 00:00 執行一次 (台灣時間早上 8 點)
  workflow_dispatch: # 允許手動觸發

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 需要完整歷史記錄才能正確合併

      - name: Set up Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/n8n-io/n8n-docs.git
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories
          git submodule update --init --recursive # 如果你的專案有子模組

      - name: Push to origin
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
