name: Sync Fork

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Update submodule URL with token
        run: |
          git config --global credential.helper store
          echo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials
          git config --file=.gitmodules submodule._submodules/insiders.url https://github.com/n8n-io/mkdocs-material-insiders.git
          git submodule sync
          git submodule deinit --all --force
          git submodule update --init --recursive

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/n8n-io/n8n-docs.git
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories

      - name: Push to origin
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
